# Generated by Django 4.2.2 on 2023-06-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
                ('nome_professor', models.CharField(max_length=100)),
                ('curso_aluno', models.CharField(max_length=3)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
